using System;
namespace SolidWorks_ASsembly_Instructor
{
    public static class FeatureNameRules
    {
        public const string Prefix = "SWASI_";
        public const string AutoPrefix = "(auto)";
        public const string OriginBase = "SWASI_Origin";
        public const string OriginPrefix = "SWASI_Origin_";
        public static bool IsReference(string name) => name != null &&
            (name.StartsWith(Prefix, StringComparison.Ordinal) || name.StartsWith(AutoPrefix + Prefix, StringComparison.Ordinal));
        public static bool IsAutoGenerated(string name) => name != null && name.StartsWith(AutoPrefix + Prefix, StringComparison.Ordinal);
        public static string ReferenceName(string name)
        {
            if (!IsReference(name)) return name ?? string.Empty;
            string value = IsAutoGenerated(name) ? name.Substring(AutoPrefix.Length) : name;
            value = value.Substring(Prefix.Length);
            return value;
        }
        // Only RefPoint features use the generated suffix. A coordinate system
        // is allowed to have a user name ending in _Point as well.
        public static string PointReferenceName(string name)
        {
            string value = ReferenceName(name);
            return IsAutoGenerated(name) && value.EndsWith("_Point", StringComparison.Ordinal)
                ? value.Substring(0, value.Length - "_Point".Length) : value;
        }
        public static bool IsOrigin(string name) => name != null &&
            (name.Equals(OriginBase, StringComparison.Ordinal) || name.StartsWith(OriginPrefix, StringComparison.Ordinal));
        public static string OriginSuffix(string name) => name != null && name.StartsWith(OriginPrefix, StringComparison.Ordinal)
            ? name.Substring(OriginPrefix.Length) : string.Empty;
        public static void ApplyProperties(RefFrameDescription refFrameDesc, string featureName)
        {
            if (refFrameDesc == null) throw new ArgumentNullException(nameof(refFrameDesc));
            if (!IsReference(featureName)) return;
            if (featureName.Contains("Vision"))
            {
                refFrameDesc.properties.SetVision(true);
            }

            if (featureName.Contains("Laser"))
            {
                refFrameDesc.properties.SetLaser(true);
            }

            if (featureName.Contains("Grip"))
            {
                refFrameDesc.properties.SetGripping(true);
            }

            if (featureName.Contains("Target"))
            {
                refFrameDesc.properties.SetTarget(true);
            }

            if (featureName.Contains("Assembly"))
            {
                refFrameDesc.properties.SetAssembly(true);
            }

            if (featureName.Contains("Glue"))
            {
                refFrameDesc.properties.SetGluePt(true);
            }
        }
    }
}
