using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using SolidWorks.Interop.sldworks;

namespace SolidWorks_ASsembly_Instructor
{
    internal sealed class SwasiFeatureCatalog
    {
        public Feature FindOrigin(ModelDoc2 document)
        {
            return Features(document).FirstOrDefault(f => FeatureNameRules.IsOrigin(f.Name));
        }

        public IReadOnlyList<SwasiFeatureItem> Read(ModelDoc2 document)
        {
            if (document == null) throw new ArgumentNullException(nameof(document));
            Feature originFeature = FindOrigin(document);
            PrecisePose origin = originFeature == null
                ? new PrecisePose()
                : ReadPreciseCoordinateSystemPose(document, originFeature);
            var result = new List<SwasiFeatureItem>();
            foreach (Feature feature in Features(document))
            {
                if (!FeatureNameRules.IsReference(feature.Name) || FeatureNameRules.IsOrigin(feature.Name)) continue;
                string type = feature.GetTypeName2();
                if (type == "CoordSys")
                    result.Add(new SwasiFeatureItem(FeatureNameRules.ReferenceName(feature.Name), "Frame",
                        ReadPreciseCoordinateSystemPose(document, feature), feature));
                else if (type == "RefPoint" && !FeatureNameRules.IsAutoGenerated(feature.Name))
                    result.Add(new SwasiFeatureItem(FeatureNameRules.ReferenceName(feature.Name), "Point",
                        ReadPoint(feature, origin.rotation), feature));
            }
            return result.OrderBy(f => f.Name, StringComparer.OrdinalIgnoreCase).ToList();
        }

        public void RenameOrigin(ModelDoc2 document, string selectedName)
        {
            if (string.IsNullOrWhiteSpace(selectedName)) throw new ArgumentException("Choose an origin name.");
            string suffix = selectedName.Trim();
            string newName = FeatureNameRules.OriginPrefix + suffix;
            Feature origin = FindOrigin(document);
            if (origin == null) throw new InvalidOperationException("The active document has no SWASI origin.");
            Feature conflict = Features(document).FirstOrDefault(f => f != origin && f.Name == newName);
            if (conflict != null) throw new InvalidOperationException($"A feature named '{newName}' already exists.");
            origin.Name = newName;
        }

        internal static CoordinateSystemDescription ReadCoordinateSystem(ModelDoc2 document, Feature feature)
        {
            // Reading a transform must not roll back the feature tree or alter
            // selection state (AccessSelections can trigger rebuild callbacks).
            var transform = document.Extension.GetCoordinateSystemTransformByName(feature.Name);
            if (transform == null)
                throw new InvalidOperationException($"Could not read coordinate system '{feature.Name}'.");
            return new CoordinateSystemDescription(CoordinateTransforms.FromCadArray((double[])transform.ArrayData))
            { name = feature.Name };
        }

        internal static CoordinateSystemDescription ReadCoordinateSystemPose(ModelDoc2 document, Feature feature)
        {
            var transform = document.Extension.GetCoordinateSystemTransformByName(feature.Name);
            if (transform == null)
                throw new InvalidOperationException($"Could not read coordinate system '{feature.Name}'.");
            return new CoordinateSystemDescription(
                CoordinateTransforms.CoordinateSystemPoseFromCadArray((double[])transform.ArrayData))
            { name = feature.Name };
        }

        internal static PrecisePose ReadPreciseCoordinateSystemPose(ModelDoc2 document, Feature feature)
        {
            var transform = document.Extension.GetCoordinateSystemTransformByName(feature.Name);
            if (transform == null) throw new InvalidOperationException($"Could not read coordinate system '{feature.Name}'.");
            var pose = PrecisePose.FromCadArray((double[])transform.ArrayData);
            pose.name = feature.Name;
            return pose;
        }

        private static PrecisePose ReadPoint(Feature feature, Quaterniond originRotation)
        {
            var point = (IRefPoint)feature.GetSpecificFeature2();
            var values = (double[])point.GetRefPoint().ArrayData;
            return new PrecisePose(new Vector3d(
                values[0] * 1000d, values[1] * 1000d, values[2] * 1000d), originRotation)
            { name = feature.Name };
        }

        internal static IEnumerable<Feature> Features(ModelDoc2 document) =>
            ((object[])document.FeatureManager.GetFeatures(false) ?? new object[0]).OfType<Feature>();
    }

    internal sealed class SwasiFeatureItem
    {
        public string Name { get; }
        public string GeometryType { get; }
        public PrecisePose Pose { get; }
        public Feature Feature { get; }
        public SwasiFeatureItem(string name, string geometryType, PrecisePose pose, Feature feature)
        { Name = name; GeometryType = geometryType; Pose = pose; Feature = feature; }
    }
}
